services:
  smart-doc-analyzer:
    build: .
    container_name: smart-doc-analyzer
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ./routes_example.json:/app/routes_example.json
